export const OPEN = 'OPEN';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_FAILURE_TIMEOUT = 'LOGIN_FAILURE_TIMEOUT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const SERVER_SELECT = 'SERVER_SELECT';
export const SERVER_LOAD_BEGIN = 'SERVER_LOAD_BEGIN';
export const SERVER_LOAD_SUCCESS = 'SERVER_LOAD_SUCCESS';
export const SERVER_LOAD_FAILURE = 'SERVER_LOAD_FAILURE';
export const SERVER_LIST_LOAD_BEGIN = 'SERVER_LIST_LOAD_BEGIN';
export const SERVER_LIST_LOAD_SUCCESS = 'SERVER_LIST_LOAD_SUCCESS';
export const SERVER_LIST_LOAD_FAILURE = 'SERVER_LIST_LOAD_FAILURE';

export const HARDWARE_POP_ADD_DIALOG = 'HARDWARE_POP_ADD_DIALOG';
export const HARDWARE_ADD_DIALOG_CANCEL = 'HARDWARE_ADD_DIALOG_CANCEL';
export const HARDWARE_ADD_DIALOG_OK = 'HARDWARE_ADD_DIALOG_OK';
export const HARDWARE_ADD_INPUT = 'HARDWARE_ADD_INPUT';

export const SETTING_SELECT_UPGRADE_BUNDLE = 'SETTING_SELECT_UPGRADE_BUNDLE';

export const ACTIVITY_GET_START = 'ACTIVITY_GET_START';
export const ACTIVITY_GET_SUCCESS = 'ACTIVITY_GET_SUCCESS';
export const ACTIVITY_GET_FAILURE = 'ACTIVITY_GET_FAILURE';
